services:
  redis:
    image: redis:latest
    command: redis-server
    ports:
      - 6379:6379

  backend:
    build:
      context: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      - CELERY_BROKER_URL=redis://host.docker.internal:6379/0
    ports:
      - 8000:8000

#  flower:
#    build:
#      context: .
#    command: celery -A app.tasks.tasks.celery flower
#    ports:
#      - 5555:5555
#    depends_on:
#      - redis

  worker-1:
    build:
      context: .
    command: celery -A app.tasks.tasks.celery worker --loglevel=INFO
    environment:
      - CELERY_BROKER_URL=redis://host.docker.internal:6379/0
    depends_on:
      - redis
